// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCnZ8GKXs7y_M7a5LHxKsa7pHwmmKl62Y',
    appId: '1:676230276974:web:cff842eaf78785c075437f',
    messagingSenderId: '676230276974',
    projectId: 'tutoru-97553',
    authDomain: 'tutoru-97553.firebaseapp.com',
    storageBucket: 'tutoru-97553.firebasestorage.app',
    measurementId: 'G-G9XMWHK4VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALu9-FUfPec-iij3YSXgOilWM1UVJDhzg',
    appId: '1:676230276974:android:9b38003732fd9e0375437f',
    messagingSenderId: '676230276974',
    projectId: 'tutoru-97553',
    storageBucket: 'tutoru-97553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdgqEvONtb0RI1AvIy8oCClArXzkApFE',
    appId: '1:676230276974:ios:ff3eeba96e5c5b7c75437f',
    messagingSenderId: '676230276974',
    projectId: 'tutoru-97553',
    storageBucket: 'tutoru-97553.firebasestorage.app',
    iosBundleId: 'com.example.tutoru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUdgqEvONtb0RI1AvIy8oCClArXzkApFE',
    appId: '1:676230276974:ios:ff3eeba96e5c5b7c75437f',
    messagingSenderId: '676230276974',
    projectId: 'tutoru-97553',
    storageBucket: 'tutoru-97553.firebasestorage.app',
    iosBundleId: 'com.example.tutoru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCnZ8GKXs7y_M7a5LHxKsa7pHwmmKl62Y',
    appId: '1:676230276974:web:8946c7b1811969e275437f',
    messagingSenderId: '676230276974',
    projectId: 'tutoru-97553',
    authDomain: 'tutoru-97553.firebaseapp.com',
    storageBucket: 'tutoru-97553.firebasestorage.app',
    measurementId: 'G-5JSCKHPL6M',
  );
}
